-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for PrintWyso.

module PrintWyso where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsWyso

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsWyso.Ident where
  prt _ (AbsWyso.Ident i) = doc $ showString i
instance Print (AbsWyso.Program' a) where
  prt i = \case
    AbsWyso.ProgramName _ alldefs -> prPrec i 0 (concatD [prt 0 alldefs])

instance Print [AbsWyso.AllDef' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (AbsWyso.Arg' a) where
  prt i = \case
    AbsWyso.ValArg _ type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])
    AbsWyso.VarArg _ type_ id_ -> prPrec i 0 (concatD [doc (showString "var"), prt 0 type_, prt 0 id_])

instance Print [AbsWyso.Arg' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (AbsWyso.AllDef' a) where
  prt i = \case
    AbsWyso.FunDef _ type_ id_ args block -> prPrec i 0 (concatD [doc (showString "def"), prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])
    AbsWyso.VarDef _ type_ id_ expr -> prPrec i 0 (concatD [doc (showString "var"), prt 0 type_, prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])

instance Print (AbsWyso.Block' a) where
  prt i = \case
    AbsWyso.BlockName _ stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [AbsWyso.Stmt' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (AbsWyso.Stmt' a) where
  prt i = \case
    AbsWyso.Empty _ -> prPrec i 0 (concatD [doc (showString ";")])
    AbsWyso.BStmt _ block -> prPrec i 0 (concatD [prt 0 block])
    AbsWyso.DefStmt _ alldef -> prPrec i 0 (concatD [prt 0 alldef])
    AbsWyso.Ass _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsWyso.Incr _ id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "++"), doc (showString ";")])
    AbsWyso.Decr _ id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "--"), doc (showString ";")])
    AbsWyso.Ret _ expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsWyso.VRet _ -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsWyso.Cond _ expr block -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    AbsWyso.CondElse _ expr block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block1, doc (showString "else"), prt 0 block2])
    AbsWyso.While _ expr block -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    AbsWyso.Break _ -> prPrec i 0 (concatD [doc (showString "break"), doc (showString ";")])
    AbsWyso.Cont _ -> prPrec i 0 (concatD [doc (showString "continue"), doc (showString ";")])
    AbsWyso.SExp _ expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])

instance Print (AbsWyso.Type' a) where
  prt i = \case
    AbsWyso.Int _ -> prPrec i 0 (concatD [doc (showString "int")])
    AbsWyso.Str _ -> prPrec i 0 (concatD [doc (showString "string")])
    AbsWyso.Bool _ -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsWyso.Void _ -> prPrec i 0 (concatD [doc (showString "void")])
    AbsWyso.Fun _ types type_ -> prPrec i 0 (concatD [doc (showString "("), prt 0 types, doc (showString ")"), doc (showString "->"), prt 0 type_])

instance Print [AbsWyso.Type' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (AbsWyso.Expr' a) where
  prt i = \case
    AbsWyso.EVar _ id_ -> prPrec i 6 (concatD [prt 0 id_])
    AbsWyso.ELitInt _ n -> prPrec i 6 (concatD [prt 0 n])
    AbsWyso.ELitTrue _ -> prPrec i 6 (concatD [doc (showString "true")])
    AbsWyso.ELitFalse _ -> prPrec i 6 (concatD [doc (showString "false")])
    AbsWyso.EApp _ id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsWyso.EString _ str -> prPrec i 6 (concatD [printString str])
    AbsWyso.Neg _ expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsWyso.Not _ expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    AbsWyso.EMul _ expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsWyso.EAdd _ expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsWyso.ERel _ expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AbsWyso.EAnd _ expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    AbsWyso.EOr _ expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
    AbsWyso.EConcat _ expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "++"), prt 0 expr2])
    AbsWyso.ELambda _ args type_ block -> prPrec i 0 (concatD [doc (showString "lambda"), doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "->"), prt 0 type_, prt 0 block])

instance Print [AbsWyso.Expr' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (AbsWyso.AddOp' a) where
  prt i = \case
    AbsWyso.Plus _ -> prPrec i 0 (concatD [doc (showString "+")])
    AbsWyso.Minus _ -> prPrec i 0 (concatD [doc (showString "-")])

instance Print (AbsWyso.MulOp' a) where
  prt i = \case
    AbsWyso.Times _ -> prPrec i 0 (concatD [doc (showString "*")])
    AbsWyso.Div _ -> prPrec i 0 (concatD [doc (showString "/")])
    AbsWyso.Mod _ -> prPrec i 0 (concatD [doc (showString "%")])

instance Print (AbsWyso.RelOp' a) where
  prt i = \case
    AbsWyso.LTH _ -> prPrec i 0 (concatD [doc (showString "<")])
    AbsWyso.LE _ -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsWyso.GTH _ -> prPrec i 0 (concatD [doc (showString ">")])
    AbsWyso.GE _ -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsWyso.EQU _ -> prPrec i 0 (concatD [doc (showString "==")])
    AbsWyso.NE _ -> prPrec i 0 (concatD [doc (showString "!=")])
